enum ActivityLevel {
  ACTIVE
  LIGHT
  MODERATE
  SEDENTARY
  VERY_ACTIVE
}

input AuthInput {
  email: String!
  password: String!
}

type AuthResponse {
  accessToken: String!
  user: UserModel!
}

type BodyMeasurementModel {
  activityLevel: ActivityLevel
  armCm: Int
  chestCm: Int
  createdAt: DateTime!
  goalWeightKg: Int
  heightCm: Int
  id: ID!
  nutritionGoal: NutritionGoal
  thighCm: Int
  updatedAt: DateTime!
  waistCm: Int
  weightKg: Int
}

input BodyMeasurementUpdateInput {
  activityLevel: ActivityLevel
  armCm: Int
  chestCm: Int
  goalWeightKg: Int
  heightCm: Int
  nutritionGoal: NutritionGoal
  thighCm: Int
  waistCm: Int
  weightKg: Int
}

input CommentCreateInput {
  content: String!
  recipeId: String!
}

type CommentModel {
  content: String!
  createdAt: DateTime!
  id: ID!
  updatedAt: DateTime!
}

input CommentUpdateInput {
  content: String!
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

enum Difficulty {
  EASY
  HARD
  MEDIUM
}

enum Gender {
  FEMALE
  MALE
}

input IngredientCreateInput {
  content: String!
  iconUrl: String!
  name: String!
  price: Float!
}

type IngredientModel {
  createdAt: DateTime!
  defaultUnit: Unit!
  id: ID!
  name: String!
  updatedAt: DateTime!
}

type Mutation {
  createComment(input: CommentCreateInput!): CommentModel!
  createIngredient(input: IngredientCreateInput!): IngredientModel!
  createOrder(input: OrderCreateInput!): OrderModel!
  createRecipe(input: RecipeCreateInput!): RecipeModel!
  deleteComment(commentId: String!): CommentModel!
  deleteIngredientById(id: String!): IngredientModel!
  deleteRecipeById(id: String!): RecipeModel!
  login(data: AuthInput!): AuthResponse!
  logout: Boolean!
  register(data: AuthInput!): AuthResponse!
  toggleLike(recipeId: String!): ToggleLikeResponse!
  updateComment(commentId: String!, input: CommentUpdateInput!): CommentModel!
  updateIngredient(id: String!, input: IngredientCreateInput!): IngredientModel!
  updateProfile(data: UserUpdateCustomInput!): UserModel!
  updateRecipe(id: String!, input: RecipeCreateInput!): RecipeModel!
}

type NutritionFact {
  carbohydrates: Float!
  createdAt: DateTime!
  fats: Float!
  fiber: Float!
  id: ID!
  proteins: Float!
  updatedAt: DateTime!
}

input NutritionFactUpdateInput {
  carbohydrates: Float!
  fats: Float!
  fiber: Float!
  proteins: Float!
}

enum NutritionGoal {
  MAINTENANCE
  MUSCLE_GAIN
  WEIGHT_LOSS
}

input OrderCreateInput {
  items: [OrderItemInput!]!
}

input OrderItemInput {
  quantity: Float! = 1
  recipeIngredientId: ID!
}

type OrderItemModel {
  createdAt: DateTime!
  id: ID!
  price: String!
  quantity: Int
  recipeIngredient: RecipeIngredientModel!
  updatedAt: DateTime!
}

type OrderModel {
  createdAt: DateTime!
  id: ID!
  items: [OrderItemModel!]!
  orderId: String!
  status: OrderStatus!
  updatedAt: DateTime!
}

enum OrderStatus {
  CANCELLED
  COMPLETED
  PENDING
  PROCESSING
}

type ProfileModel {
  age: Int
  bio: String
  createdAt: DateTime!
  fullName: String!
  gender: Gender
  id: ID!
  updatedAt: DateTime!
}

input ProfileUpdateInput {
  age: Int
  bio: String
  fullName: String
  gender: Gender
}

type Query {
  adminRecipes: [RecipeModel!]!
  ingredientById(id: String!): IngredientModel!
  ingredients: [IngredientModel!]!
  myOrders: [OrderModel!]!
  newTokens: AuthResponse!
  profile: UserModel!
  recipeById(id: String!): RecipeModel!
  recipeBySlug(slug: String!): RecipeModel!
  recipes(input: RecipesQueryInput!): [RecipeModel!]!
  users: [UserModel!]!
}

input RecipeCreateInput {
  calories: Int!
  cookingTime: Int!
  description: String!
  difficulty: Difficulty!
  ingredients: [RecipeIngredientInput!]
  nutritionFact: NutritionFactUpdateInput
  recipeSteps: [RecipeStepInput!]
  slug: String!
  tags: String
  title: String!
}

input RecipeIngredientInput {
  ingredientId: ID!
  quantity: Float!
  unit: Unit!
}

type RecipeIngredientModel {
  createdAt: DateTime!
  id: ID!
  ingredient: IngredientModel!
  quantity: Float!
  unit: Unit!
  updatedAt: DateTime!
}

type RecipeModel {
  author: UserModel!
  authorId: String!
  calories: Int!
  cookingTime: Int!
  createdAt: DateTime!
  description: String!
  difficulty: Difficulty!
  id: ID!
  likes: Int
  nutritionFact: NutritionFact
  recipeIngredients: [RecipeIngredientModel!]
  recipeSteps: [RecipeStepModel!]
  slug: String!
  tags: [RecipeTagModel!]
  title: String!
  updatedAt: DateTime!
}

input RecipeStepInput {
  description: String!
  order: Int!
  title: String!
}

type RecipeStepModel {
  createdAt: DateTime!
  description: String!
  id: ID!
  order: Int!
  recipe: RecipeModel!
  recipeId: String!
  title: String!
  updatedAt: DateTime!
}

type RecipeTagModel {
  createdAt: DateTime!
  id: ID!
  name: String!
  updatedAt: DateTime!
}

input RecipesQueryInput {
  limit: Int! = 10
  page: Int! = 1
  searchTerm: String
  sort: String
}

enum Role {
  ADMIN
  USER
}

type ToggleLikeResponse {
  liked: Boolean!
}

enum Unit {
  CLOVES
  GRAM
  MILLILITER
  PIECE
  TABLESPOON
  TEASPOON
}

type UserModel {
  createdAt: DateTime!
  email: String!
  id: ID!
  measurements: BodyMeasurementModel
  profile: ProfileModel
  role: Role!
  updatedAt: DateTime!
}

input UserUpdateCustomInput {
  email: String
  measurements: BodyMeasurementUpdateInput
  password: String
  profile: ProfileUpdateInput
}